config/routes.rb
Rails.application.routes.draw do
  get 'page_generator_controller/home'

  get 'page_generator_controller/about'

  get 'page_generator_controller/contact'

  get 'page_generator_controller/faq'

  get 'page_generator_controller/archive'

  resources :homework_blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/homework_blog.rb
class HomeworkBlog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homework_blogs_controller.rb
class HomeworkBlogsController < ApplicationController
  before_action :set_homework_blog, only: [:show, :edit, :update, :destroy]

  # GET /homework_blogs
  # GET /homework_blogs.json
  def index
    @homework_blogs = HomeworkBlog.all
  end

  # GET /homework_blogs/1
  # GET /homework_blogs/1.json
  def show
  end

  # GET /homework_blogs/new
  def new
    @homework_blog = HomeworkBlog.new
  end

  # GET /homework_blogs/1/edit
  def edit
  end

  # POST /homework_blogs
  # POST /homework_blogs.json
  def create
    @homework_blog = HomeworkBlog.new(homework_blog_params)

    respond_to do |format|
      if @homework_blog.save
        format.html { redirect_to @homework_blog, notice: 'Homework blog was successfully created.' }
        format.json { render :show, status: :created, location: @homework_blog }
      else
        format.html { render :new }
        format.json { render json: @homework_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homework_blogs/1
  # PATCH/PUT /homework_blogs/1.json
  def update
    respond_to do |format|
      if @homework_blog.update(homework_blog_params)
        format.html { redirect_to @homework_blog, notice: 'Homework blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework_blog }
      else
        format.html { render :edit }
        format.json { render json: @homework_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homework_blogs/1
  # DELETE /homework_blogs/1.json
  def destroy
    @homework_blog.destroy
    respond_to do |format|
      format.html { redirect_to homework_blogs_url, notice: 'Homework blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework_blog
      @homework_blog = HomeworkBlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_blog_params
      params.require(:homework_blog).permit(:title, :body, :published)
    end
end

app/controllers/page_generator_controller_controller.rb
class PageGeneratorControllerController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def faq
  end

  def archive
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homework_blogs_helper.rb
module HomeworkBlogsHelper
end

app/helpers/page_generator_controller_helper.rb
module PageGeneratorControllerHelper
end

app/views/homework_blogs/_form.html.erb
<%= form_with(model: homework_blog, local: true) do |form| %>
  <% if homework_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homework_blog.errors.count, "error") %> prohibited this homework_blog from being saved:</h2>

      <ul>
      <% homework_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :homework_blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :homework_blog_body %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published, id: :homework_blog_published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homework_blogs/edit.html.erb
<h1>Editing Homework Blog</h1>

<%= render 'form', homework_blog: @homework_blog %>

<%= link_to 'Show', @homework_blog %> |
<%= link_to 'Back', homework_blogs_path %>

app/views/homework_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homework Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homework_blogs.each do |homework_blog| %>
      <tr>
        <td><%= homework_blog.title %></td>
        <td><%= homework_blog.body %></td>
        <td><%= homework_blog.published %></td>
        <td><%= link_to 'Show', homework_blog %></td>
        <td><%= link_to 'Edit', edit_homework_blog_path(homework_blog) %></td>
        <td><%= link_to 'Destroy', homework_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework Blog', new_homework_blog_path %>

app/views/homework_blogs/new.html.erb
<h1>New Homework Blog</h1>

<%= render 'form', homework_blog: @homework_blog %>

<%= link_to 'Back', homework_blogs_path %>

app/views/homework_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @homework_blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @homework_blog.body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @homework_blog.published %>
</p>

<%= link_to 'Edit', edit_homework_blog_path(@homework_blog) %> |
<%= link_to 'Back', homework_blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page_generator_controller/about.html.erb
<h1>PageGeneratorController#about</h1>
<p>Find me in app/views/page_generator_controller/about.html.erb</p>

app/views/page_generator_controller/archive.html.erb
<h1>PageGeneratorController#archive</h1>
<p>Find me in app/views/page_generator_controller/archive.html.erb</p>

app/views/page_generator_controller/contact.html.erb
<h1>PageGeneratorController#contact</h1>
<p>Find me in app/views/page_generator_controller/contact.html.erb</p>

app/views/page_generator_controller/faq.html.erb
<h1>PageGeneratorController#faq</h1>
<p>Find me in app/views/page_generator_controller/faq.html.erb</p>

app/views/page_generator_controller/home.html.erb
<h1>PageGeneratorController#home</h1>
<p>Find me in app/views/page_generator_controller/home.html.erb</p>